version: '3.9'

services:
  api-server:
    image: api-server:latest
    network_mode: host
    restart: always
    volumes:
      - ./logs.txt:/app/logs.txt
      - ./database.db:/app/database.db

  bot-service:
    image: bot-service:latest
    network_mode: host
    restart: always
    volumes:
      - ./logs.txt:/app/logs.txt
